name: flutter_mybutton
description: "my flutter button"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0-227.0.dev <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mywidgets.flutter_mybutton
        pluginClass: FlutterMybuttonPlugin
      ios:
        pluginClass: FlutterMybuttonPlugin

