name: flutter_mylocation_example
description: "Demonstrates how to use the flutter_mylocation plugin."
publish_to: 'none'

environment:
  sdk: '>=3.5.0-227.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_mylocation:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

